import type { SecretKnowledgeCheckQuestion, KnowledgeCheckTopic } from "./types";

export const fallbackKnowledgeCheckBank: SecretKnowledgeCheckQuestion[] = [
  {
    id: "html-1",
    topic: "html",
    question: "Which element is best for a self-contained piece of content?",
    questionBg: "Кой елемент е най-подходящ за самостоятелна част от съдържание?",
    options: ["<div>", "<article>", "<span>", "<b>"],
    optionsBg: ["<div>", "<article>", "<span>", "<b>"],
    correctIndex: 1,
    explanation: "article groups independent content like cards or posts.",
    explanationBg: "article групира самостоятелно съдържание като карти или постове."
  },
  {
    id: "html-2",
    topic: "html",
    question: "What does semantic HTML improve?",
    questionBg: "Какво подобрява семантичният HTML?",
    options: ["Only colors", "Accessibility and structure", "Database speed", "Git commits"],
    optionsBg: ["Само цветовете", "Достъпност и структура", "Скорост на базата", "Git commits"],
    correctIndex: 1,
    explanation: "Semantic tags help screen readers and make layouts easier to reason about.",
    explanationBg: "Семантичните тагове помагат на screen readers и правят layout-а по-ясен."
  },
  {
    id: "html-3",
    topic: "html",
    question: "Which explicit button type submits a form?",
    questionBg: "Кой изрично зададен тип бутон изпраща формуляр?",
    options: ['type="reset"', 'type="button"', 'type="submit"', 'type="menu"'],
    optionsBg: ['type="reset"', 'type="button"', 'type="submit"', 'type="menu"'],
    correctIndex: 2,
    explanation: 'type="submit" clearly states that the button submits the form.',
    explanationBg: 'type="submit" ясно задава, че бутонът изпраща формуляра.'
  },
  {
    id: "css-1",
    topic: "css",
    question: "Which property creates space inside an element?",
    questionBg: "Кое свойство създава пространство вътре в елемент?",
    options: ["margin", "padding", "border-radius", "z-index"],
    optionsBg: ["margin", "padding", "border-radius", "z-index"],
    correctIndex: 1,
    explanation: "Padding adds inner space; margin adds outer space.",
    explanationBg: "Padding добавя вътрешно пространство; margin — външно."
  },
  {
    id: "css-2",
    topic: "css",
    question: "Which declaration creates two equal grid columns?",
    questionBg: "Коя декларация създава две еднакво широки колони в CSS Grid?",
    options: ["grid-template-columns: 1fr 1fr", "grid-template-rows: 1fr 1fr", "text-align: center", "position: fixed"],
    optionsBg: ["grid-template-columns: 1fr 1fr", "grid-template-rows: 1fr 1fr", "text-align: center", "position: fixed"],
    correctIndex: 0,
    explanation: "Two 1fr tracks divide the available horizontal space equally.",
    explanationBg: "Две колони по 1fr разделят наличното хоризонтално пространство поравно."
  },
  {
    id: "css-3",
    topic: "css",
    question: "What does border-radius change?",
    questionBg: "Какво променя border-radius?",
    options: ["Text color", "Corner roundness", "Font size", "Line height"],
    optionsBg: ["Цвета на текста", "Заобленост на ъглите", "Размера на шрифта", "Височина на реда"],
    correctIndex: 1,
    explanation: "border-radius rounds the corners of a box.",
    explanationBg: "border-radius заобля ъглите на box."
  },
  {
    id: "js-1",
    topic: "javascript",
    question: "Which keyword should you prefer for values that do not change?",
    questionBg: "Коя дума е по-добра за стойности, които не се променят?",
    options: ["var", "let", "const", "static"],
    optionsBg: ["var", "let", "const", "static"],
    correctIndex: 2,
    explanation: "const prevents reassignment and makes intent clearer.",
    explanationBg: "const спира повторно присвояване и прави кода по-ясен."
  },
  {
    id: "js-2",
    topic: "javascript",
    question: "What does a function return if there is no return statement?",
    questionBg: "Какво връща функция без return?",
    options: ["0", "null", "undefined", "false"],
    optionsBg: ["0", "null", "undefined", "false"],
    correctIndex: 2,
    explanation: "JavaScript functions return undefined by default.",
    explanationBg: "JavaScript функциите връщат undefined по подразбиране."
  },
  {
    id: "js-3",
    topic: "javascript",
    question: "Which method adds one item to the end of an array?",
    questionBg: "Кой метод добавя един елемент в края на масив?",
    options: ["push()", "pop()", "shift()", "slice()"],
    optionsBg: ["push()", "pop()", "shift()", "slice()"],
    correctIndex: 0,
    explanation: "push() mutates the array and returns the new length.",
    explanationBg: "push() променя масива и връща новата дължина."
  },
  {
    id: "dom-1",
    topic: "dom",
    question: "Which API listens for user clicks?",
    questionBg: "Кой API слуша за кликове на потребителя?",
    options: ["addEventListener('click')", "querySelector('click')", "JSON.parse()", "fetch()"],
    optionsBg: ["addEventListener('click')", "querySelector('click')", "JSON.parse()", "fetch()"],
    correctIndex: 0,
    explanation: "Event listeners connect user actions to your JavaScript logic.",
    explanationBg: "Event listeners свързват действията на потребителя с JavaScript логиката."
  },
  {
    id: "dom-2",
    topic: "dom",
    question: "What does document.querySelector('.card') return?",
    questionBg: "Какво връща document.querySelector('.card')?",
    options: ["All matching elements", "The first matching element, or null", "A CSS file", "The last click event"],
    optionsBg: ["Всички съвпадащи елементи", "Първия съвпадащ елемент или null", "CSS файл", "Последното събитие click"],
    correctIndex: 1,
    explanation: "querySelector returns the first match for a CSS selector, or null when nothing matches.",
    explanationBg: "querySelector връща първото съвпадение за CSS селектор или null, когато няма такова."
  },
  {
    id: "dom-3",
    topic: "dom",
    question: "A form field contains invalid data. What is the clearest response?",
    questionBg: "Поле във формуляр съдържа невалидни данни. Коя реакция е най-ясна?",
    options: ["Ignore the input", "Delete the whole form", "Show a specific message next to the field and keep the entered value", "Reload without explanation"],
    optionsBg: ["Да се игнорира въведеното", "Да се изтрие целият формуляр", "Да се покаже конкретно съобщение до полето и да се запази въведеното", "Да се презареди без обяснение"],
    correctIndex: 2,
    explanation: "A nearby, specific message helps the user identify and correct the problem.",
    explanationBg: "Конкретно съобщение до полето помага на потребителя да открие и поправи проблема."
  },
  {
    id: "fetch-1",
    topic: "fetch",
    question: "What does fetch() return?",
    questionBg: "Какво връща fetch()?",
    options: ["JSON directly", "A Promise", "An array", "A DOM node"],
    optionsBg: ["JSON директно", "Promise", "Масив", "DOM node"],
    correctIndex: 1,
    explanation: "fetch resolves to a Response object after the network request.",
    explanationBg: "fetch връща Response обект след мрежовата заявка."
  },
  {
    id: "fetch-2",
    topic: "fetch",
    question: "Which HTTP method is commonly used to create data?",
    questionBg: "Кой HTTP метод се ползва най-често за създаване на данни?",
    options: ["GET", "POST", "DELETE", "OPTIONS"],
    optionsBg: ["GET", "POST", "DELETE", "OPTIONS"],
    correctIndex: 1,
    explanation: "POST sends a body to create or submit new data.",
    explanationBg: "POST изпраща body за създаване или изпращане на нови данни."
  },
  {
    id: "fetch-3",
    topic: "fetch",
    question: "What should an interface do when a network request fails?",
    questionBg: "Какво трябва да направи интерфейсът, когато мрежова заявка е неуспешна?",
    options: ["Pretend the data was saved", "Show a clear error and offer a safe retry", "Erase all local work", "Keep loading forever"],
    optionsBg: ["Да се престори, че данните са записани", "Да покаже ясна грешка и безопасна възможност за нов опит", "Да изтрие цялата локална работа", "Да зарежда безкрайно"],
    correctIndex: 1,
    explanation: "Clear feedback and a controlled retry help the user recover without losing work.",
    explanationBg: "Ясната обратна връзка и контролиран нов опит помагат без загуба на работа."
  },
  {
    id: "react-1",
    topic: "react",
    question: "What is a React component?",
    questionBg: "Какво е React component?",
    options: ["A database table", "A reusable UI function", "A CSS file", "A Git branch"],
    optionsBg: ["Таблица в база", "Преизползваема UI функция", "CSS файл", "Git branch"],
    correctIndex: 1,
    explanation: "Components let you split UI into reusable pieces with props and state.",
    explanationBg: "Components разделят UI на преизползваеми части с props и state."
  },
  {
    id: "react-2",
    topic: "react",
    question: "How do you pass data into a child component?",
    questionBg: "Как подаваш данни към child component?",
    options: ["With props", "With SQL", "With padding", "With return only"],
    optionsBg: ["С props", "С SQL", "С padding", "Само с return"],
    correctIndex: 0,
    explanation: "Props are the standard way to pass read-only data into components.",
    explanationBg: "Props са стандартният начин да подадеш read-only данни към components."
  },
  {
    id: "react-3",
    topic: "react",
    question: "When should state be used in an interface component?",
    questionBg: "Кога е подходящо да се използва state в компонент на интерфейса?",
    options: ["For a value that changes after user interaction", "For a fixed heading that never changes", "To replace every CSS rule", "To store a private server key"],
    optionsBg: ["За стойност, която се променя след действие на потребителя", "За постоянно заглавие, което не се променя", "За замяна на всяко CSS правило", "За съхраняване на таен сървърен ключ"],
    correctIndex: 0,
    explanation: "State represents data that can change and should cause the component to update.",
    explanationBg: "State представя данни, които се променят и трябва да обновят компонента."
  },
  {
    id: "api-1",
    topic: "api",
    question: "What makes an API response easier for a client to use safely?",
    questionBg: "Какво прави отговора на API по-лесен за безопасно използване от клиента?",
    options: ["A consistent data and error structure", "A different field name on every request", "Secrets included for debugging", "Success status for every error"],
    optionsBg: ["Постоянна структура за данни и грешки", "Различно име на полето при всяка заявка", "Включени тайни за отстраняване на грешки", "Успешен статус за всяка грешка"],
    correctIndex: 0,
    explanation: "A consistent contract lets the client validate data and handle failures predictably.",
    explanationBg: "Постоянният формат позволява на клиента да проверява данните и да обработва грешките предвидимо."
  },
  {
    id: "api-2",
    topic: "api",
    question: "Which HTTP status code fits a missing required field?",
    questionBg: "Кой HTTP status code е подходящ за липсващо задължително поле?",
    options: ["200", "400", "404", "500"],
    optionsBg: ["200", "400", "404", "500"],
    correctIndex: 1,
    explanation: "400 Bad Request tells the client the input was invalid.",
    explanationBg: "400 Bad Request казва на клиента, че входът е невалиден."
  },
  {
    id: "api-3",
    topic: "api",
    question: "Where should a private API key be stored in a web application?",
    questionBg: "Къде трябва да се съхранява частен API ключ в уеб приложение?",
    options: ["In browser code", "In a public repository", "In protected server-side configuration", "In an image file"],
    optionsBg: ["В кода на браузъра", "В публично хранилище", "В защитена сървърна конфигурация", "Във файл с изображение"],
    correctIndex: 2,
    explanation: "Private keys must remain on the server and must not be sent to the browser or committed publicly.",
    explanationBg: "Частните ключове трябва да останат на сървъра и да не се изпращат към браузъра или публично хранилище."
  },
  {
    id: "api-4",
    topic: "api",
    question: "What status should a protected API endpoint return when authentication is missing?",
    questionBg: "Какъв статус трябва да върне защитена API крайна точка, когато липсва удостоверяване?",
    options: ["200 with empty body", "401 Unauthorized", "302 to homepage", "500"],
    optionsBg: ["200 с празно body", "401 Unauthorized", "302 към homepage", "500"],
    correctIndex: 1,
    explanation: "401 clearly signals that authentication is required.",
    explanationBg: "401 ясно показва, че е нужна автентикация."
  },
  {
    id: "api-5",
    topic: "api",
    question: "What should a server do before saving data received from a client?",
    questionBg: "Какво трябва да направи сървърът, преди да запише данни, получени от клиент?",
    options: ["Trust every field", "Validate type, range, length, and permission", "Remove all error messages", "Save the data twice"],
    optionsBg: ["Да се довери на всяко поле", "Да провери тип, диапазон, дължина и право за действие", "Да премахне всички съобщения за грешки", "Да запише данните два пъти"],
    correctIndex: 1,
    explanation: "Server-side validation protects data even when browser checks are bypassed.",
    explanationBg: "Сървърната проверка защитава данните дори когато проверките в браузъра са заобиколени."
  },
  {
    id: "quiz-gen-1",
    topic: "quiz-generator",
    question: "What input does a knowledge-check builder need at minimum?",
    questionBg: "Какво трябва да има създателят на самопроверка като минимум?",
    options: ["A learning objective and a reviewed question bank", "Only a timer and a title", "Only the correct answers", "A list of student passwords"],
    optionsBg: ["Учебна цел и проверена банка от въпроси", "Само таймер и заглавие", "Само верните отговори", "Списък с пароли на ученици"],
    correctIndex: 0,
    explanation: "Questions should measure a stated learning objective and be reviewed for correctness and clarity.",
    explanationBg: "Въпросите трябва да измерват заявена учебна цел и да са проверени за вярност и яснота."
  },
  {
    id: "quiz-gen-2",
    topic: "quiz-generator",
    question: "Why should a knowledge check store an explanation with the correct answer?",
    questionBg: "Защо самопроверката трябва да пази обяснение към верния отговор?",
    options: ["To give useful feedback after an attempt", "To make every answer look correct", "To replace the question", "To reveal student passwords"],
    optionsBg: ["За да даде полезна обратна връзка след опита", "За да изглежда всеки отговор верен", "За да замени въпроса", "За да разкрива пароли на ученици"],
    correctIndex: 0,
    explanation: "An explanation helps the learner understand the reasoning instead of seeing only a score.",
    explanationBg: "Обяснението помага на ученика да разбере логиката, вместо да вижда само резултат."
  },
  {
    id: "quiz-gen-3",
    topic: "quiz-generator",
    question: "Which question is the fairest knowledge check?",
    questionBg: "Кой въпрос е най-подходящ за справедлива самопроверка?",
    options: ["A clear question linked to a taught objective with one defensible answer", "A trick question on an untaught detail", "A question with two equally correct answers", "A question whose wording reveals the answer"],
    optionsBg: ["Ясен въпрос по изучавана цел с един защитим верен отговор", "Подвеждащ въпрос за непреподаван детайл", "Въпрос с два еднакво верни отговора", "Въпрос, чиято формулировка подсказва отговора"],
    correctIndex: 0,
    explanation: "A fair item measures what was taught, uses clear language, and has one unambiguous answer.",
    explanationBg: "Справедливият въпрос измерва преподаваното, използва ясен език и има един недвусмислен отговор."
  },
  {
    id: "fullstack-1",
    topic: "fullstack",
    question: "Which sequence best describes submitting data in a full-stack application?",
    questionBg: "Коя последователност най-добре описва изпращането на данни в пълно уеб приложение?",
    options: ["Interface → server validation → database → response", "Database → CSS → keyboard → response", "Interface → public secret → database → no response", "Browser → printer → database → image"],
    optionsBg: ["Интерфейс → сървърна проверка → база данни → отговор", "База данни → CSS → клавиатура → отговор", "Интерфейс → публична тайна → база данни → без отговор", "Браузър → принтер → база данни → изображение"],
    correctIndex: 0,
    explanation: "The client sends input, the server validates and stores it, then returns a clear result.",
    explanationBg: "Клиентът изпраща данните, сървърът ги проверява и записва, след което връща ясен резултат."
  },
  {
    id: "fullstack-2",
    topic: "fullstack",
    question: "Which information must not be stored as plain text in browser local storage?",
    questionBg: "Коя информация не трябва да се съхранява като обикновен текст в локалното хранилище на браузъра?",
    options: ["A selected color theme", "An unfinished filter choice", "Passwords and private API keys", "The current page number"],
    optionsBg: ["Избраната цветова тема", "Недовършен избор на филтър", "Пароли и частни API ключове", "Номерът на текущата страница"],
    correctIndex: 2,
    explanation: "Browser storage is accessible to page scripts and is not a safe vault for passwords or private keys.",
    explanationBg: "Локалното хранилище е достъпно за скриптовете на страницата и не е безопасно място за пароли или частни ключове."
  },
  {
    id: "fullstack-3",
    topic: "fullstack",
    question: "Which page should require an authenticated user?",
    questionBg: "Коя страница трябва да изисква удостоверен потребител?",
    options: ["A public school homepage", "A personal page with grades and progress", "A public contact page", "A sign-in page"],
    optionsBg: ["Публична начална страница на училище", "Лична страница с оценки и напредък", "Публична страница за контакт", "Страница за вход"],
    correctIndex: 1,
    explanation: "Personal educational data should be available only to authorized users.",
    explanationBg: "Личните образователни данни трябва да са достъпни само за упълномощени потребители."
  },
  {
    id: "ai-1",
    topic: "ai",
    question: "What is the main difference between a fixed rule and a learned model?",
    questionBg: "Каква е основната разлика между зададено правило и научен модел?",
    options: ["A rule is written directly, while a model finds patterns from examples", "A model is always correct", "A rule requires more training data", "There is no difference"],
    optionsBg: ["Правилото се задава пряко, а моделът открива закономерности от примери", "Моделът винаги е верен", "Правилото изисква повече обучаващи данни", "Няма разлика"],
    correctIndex: 0,
    explanation: "Rules are specified by people; learned models are fitted from data and can still make mistakes.",
    explanationBg: "Правилата се задават от хора, а научените модели се настройват по данни и могат да грешат."
  },
  {
    id: "ai-2",
    topic: "ai",
    question: "What should not be included in a prompt sent to a public AI service?",
    questionBg: "Какво не трябва да се включва в заявка към публична AI услуга?",
    options: ["A general topic", "An invented example", "Passwords, personal data, or confidential documents", "The desired answer format"],
    optionsBg: ["Обща тема", "Измислен пример", "Пароли, лични данни или поверителни документи", "Желаният формат на отговора"],
    correctIndex: 2,
    explanation: "Sensitive data may be processed outside the school's control and should not be shared without authorization.",
    explanationBg: "Чувствителните данни може да се обработват извън контрола на училището и не трябва да се споделят без разрешение."
  },
  {
    id: "ai-3",
    topic: "ai",
    question: "An AI answer sounds confident but gives no sources. What should you do?",
    questionBg: "Отговор от AI звучи уверено, но няма източници. Какво трябва да направиш?",
    options: ["Submit it as a proven fact", "Verify its claims with reliable independent sources", "Add personal data to improve it", "Remove any conflicting evidence"],
    optionsBg: ["Да го предадеш като доказан факт", "Да провериш твърденията в надеждни независими източници", "Да добавиш лични данни, за да го подобриш", "Да премахнеш всяко противоречащо доказателство"],
    correctIndex: 1,
    explanation: "A confident tone does not guarantee accuracy; the learner remains responsible for verification.",
    explanationBg: "Увереният тон не гарантира вярност; ученикът остава отговорен за проверката."
  },
  {
    id: "mobile-1",
    topic: "mobile",
    question: "Which button height is the easiest practical target to tap among these options?",
    questionBg: "Коя от тези височини е най-практична за лесно натискане на бутон?",
    options: ["12px", "24px", "32px", "48px"],
    optionsBg: ["12px", "24px", "32px", "48px"],
    correctIndex: 3,
    explanation: "Around 44–48 CSS pixels is a common practical target for comfortable touch interaction.",
    explanationBg: "Около 44–48 CSS пиксела е честа практическа цел за удобно взаимодействие чрез докосване."
  },
  {
    id: "mobile-2",
    topic: "mobile",
    question: "What does width=device-width do?",
    questionBg: "Какво прави width=device-width?",
    options: ["Makes every element 100 pixels wide", "Matches the layout viewport to the device width", "Forces landscape mode", "Disables page zoom by itself"],
    optionsBg: ["Прави всеки елемент широк 100 пиксела", "Съпоставя ширината на оформлението с ширината на устройството", "Налага хоризонтален режим", "Самостоятелно забранява увеличаването"],
    correctIndex: 1,
    explanation: "It prevents mobile browsers from rendering a tiny scaled desktop page.",
    explanationBg: "Предотвратява показването на умалена настолна страница в мобилен браузър."
  },
  {
    id: "mobile-3",
    topic: "mobile",
    question: "How should a row of wide content cards usually adapt to a narrow phone screen?",
    questionBg: "Как обикновено трябва да се адаптира ред от широки карти към тесен телефонен екран?",
    options: ["Keep five narrow columns", "Stack cards in one readable column", "Hide all card text", "Require sideways scrolling for the whole page"],
    optionsBg: ["Да запази пет тесни колони", "Да подреди картите в една четима колона", "Да скрие целия текст в картите", "Да изисква странично превъртане на цялата страница"],
    correctIndex: 1,
    explanation: "A single-column stack preserves readable content and avoids page-level horizontal scrolling.",
    explanationBg: "Една колона запазва съдържанието четимо и избягва хоризонталното превъртане на страницата."
  },
  {
    id: "product-1",
    topic: "product",
    question: "What is the main purpose of a first prototype?",
    questionBg: "Каква е основната цел на първия прототип?",
    options: ["To include every planned feature", "To test the riskiest assumption quickly with users", "To avoid feedback until launch", "To look finished even if it cannot be used"],
    optionsBg: ["Да съдържа всяка планирана функция", "Бързо да провери най-рисковото допускане с потребители", "Да избегне обратна връзка до пускането", "Да изглежда завършен, дори да не може да се използва"],
    correctIndex: 1,
    explanation: "A prototype is a quick, low-cost way to learn whether an idea solves the intended problem.",
    explanationBg: "Прототипът е бърз и евтин начин да се провери дали идеята решава поставения проблем."
  },
  {
    id: "product-2",
    topic: "product",
    question: "Which interview question is most useful when researching a user problem?",
    questionBg: "Кой въпрос е най-полезен при проучване на потребителски проблем?",
    options: ["Our idea is great, isn't it?", "Tell me about the last time you faced this problem", "Would you buy every feature we add?", "Why do you dislike our design?"],
    optionsBg: ["Нашата идея е страхотна, нали?", "Разкажи ми за последния път, когато срещна този проблем", "Би ли купил всяка функция, която добавим?", "Защо не харесваш нашия дизайн?"],
    correctIndex: 1,
    explanation: "A neutral question about real past behavior produces more reliable evidence than a leading question.",
    explanationBg: "Неутралният въпрос за реално минало поведение дава по-надеждни данни от подвеждащ въпрос."
  },
  {
    id: "product-3",
    topic: "product",
    question: "Which is the strongest evidence that a prototype is useful?",
    questionBg: "Кое е най-силното доказателство, че прототипът е полезен?",
    options: ["The team says it is excellent", "Relevant users complete the main task and explain the benefit", "The presentation has many slides", "The logo uses a fashionable color"],
    optionsBg: ["Екипът казва, че е отличен", "Подходящи потребители изпълняват основната задача и обясняват ползата", "Презентацията има много слайдове", "Логото използва модерен цвят"],
    correctIndex: 1,
    explanation: "Observed behavior from target users is stronger evidence than the creators' opinion or visual polish.",
    explanationBg: "Наблюдаваното поведение на целеви потребители е по-силно доказателство от мнението на създателите или добрия външен вид."
  }
];

export const fallbackLessonKnowledgeCheckMap: Record<string, KnowledgeCheckTopic> = {
  "1": "html",
  "2": "css",
  "8": "javascript",
  "9": "javascript",
  "10": "dom",
  "11": "fetch",
  "12": "react",
  "13": "quiz-generator",
  "3": "api",
  "14": "api",
  "15": "api",
  "16": "api",
  "17": "api",
  "18": "api",
  "4": "fullstack",
  "19": "fullstack",
  "20": "fullstack",
  "21": "fullstack",
  "22": "fullstack",
  "23": "fullstack",
  "24": "fullstack",
  "5": "ai",
  "25": "ai",
  "26": "ai",
  "27": "ai",
  "28": "ai",
  "29": "ai",
  "30": "ai",
  "6": "mobile",
  "31": "mobile",
  "32": "mobile",
  "33": "mobile",
  "34": "mobile",
  "35": "mobile",
  "36": "mobile",
  "7": "product",
  "37": "product",
  "38": "product",
  "39": "product",
  "40": "product",
  "41": "product",
  "42": "product",
  "43": "api",
  "44": "api",
  "45": "api",
  "46": "api",
  "47": "fullstack",
  "48": "fullstack",
  "49": "fullstack",
  "50": "fullstack",
  "51": "fullstack",
  "52": "product",
  "53": "product",
  "54": "product",
  "55": "product",
  "56": "product",
  "57": "product",
  "58": "product",
  "59": "product",
  "60": "product",
  "61": "product",
  "62": "product",
  "63": "product"
};

// Compatibility aliases for existing imports while the public terminology changes.
export const fallbackQuestionBank = fallbackKnowledgeCheckBank;
export const fallbackLessonTopicMap = fallbackLessonKnowledgeCheckMap;
